import pandas as pd
import numpy as np
import io
import zipfile
import uuid
import datetime
from typing import Literal, Dict, Optional
from app.core.database import supabase

class ExportService:
    @staticmethod
    def to_csv(df: pd.DataFrame) -> bytes:
        output = io.StringIO()
        df.to_csv(output, index=False)
        return output.getvalue().encode('utf-8')

    @staticmethod
    def to_json(df: pd.DataFrame, format: Literal["array", "ndjson"] = "array") -> bytes:
        output = io.StringIO()
        if format == "ndjson":
            df.to_json(output, orient="records", lines=True)
        else:
            df.to_json(output, orient="records", indent=2)
        return output.getvalue().encode('utf-8')

    @staticmethod
    def to_zip(dataframes: Dict[str, pd.DataFrame]) -> bytes:
        output = io.BytesIO()
        with zipfile.ZipFile(output, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            for table_name, df in dataframes.items():
                csv_data = io.StringIO()
                df.to_csv(csv_data, index=False)
                zip_file.writestr(f"{table_name}.csv", csv_data.getvalue())
        return output.getvalue()

    @staticmethod
    def to_notebook(df: pd.DataFrame, target_col: Optional[str] = None) -> bytes:
        import json
        
        # Detect task type
        task_type = "classification"
        if target_col and target_col in df.columns:
            if np.issubdtype(df[target_col].dtype, np.number) and df[target_col].nunique() > 10:
                task_type = "regression"

        cells = [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# Synthetic Dataset Analysis & Baseline Model\n",
                    "Generated by **SyntheticEngine**"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import pandas as pd\n",
                    "import numpy as np\n",
                    "import matplotlib.pyplot as plt\n",
                    "import seaborn as sns\n",
                    "from sklearn.model_selection import train_test_split\n",
                    "from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor\n",
                    "from sklearn.metrics import classification_report, mean_squared_error, r2_score\n",
                    "from sklearn.preprocessing import LabelEncoder\n",
                    "\n",
                    "sns.set_theme(style=\"whitegrid\")\n",
                    "print(\"Libraries loaded.\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## 1. Load Dataset"]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Note: Ensure 'data.csv' is in the same directory as this notebook\n",
                    "df = pd.read_csv('data.csv')\n",
                    "print(f\"Dataset Shape: {df.shape}\")\n",
                    "df.head()"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## 2. Exploratory Data Analysis (EDA)"]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "print(\"Column Types:\")\n",
                    "print(df.dtypes)\n",
                    "\n",
                    "print(\"\\nMissing Values:\")\n",
                    "print(df.isnull().sum())\n",
                    "\n",
                    "plt.figure(figsize=(10, 6))\n",
                    "sns.heatmap(df.isnull(), cbar=False, yticklabels=False, cmap='viridis')\n",
                    "plt.title('Missing Data Heatmap')\n",
                    "plt.show()"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## 3. Visualizations"]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Visualizing the first few numeric columns\n",
                    "numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()\n",
                    "for col in numeric_cols[:3]:\n",
                    "    plt.figure(figsize=(8, 4))\n",
                    "    sns.histplot(df[col], kde=True)\n",
                    "    plt.title(f'Distribution of {col}')\n",
                    "    plt.show()"
                ]
            }
        ]

        # Add modelling section if target is provided
        if target_col and target_col in df.columns:
            cells.extend([
                {
                    "cell_type": "markdown",
                    "metadata": {},
                    "source": [f"## 4. Baseline Machine Learning Model ({task_type.capitalize()})\n", f"Target variable: `{target_col}`"]
                },
                {
                    "cell_type": "code",
                    "execution_count": None,
                    "metadata": {},
                    "outputs": [],
                    "source": [
                        "# Prepare Data\n",
                        "X = df.drop(columns=['" + target_col + "'])\n",
                        "y = df['" + target_col + "']\n",
                        "\n",
                        "# Basic Preprocessing\n",
                        "X = pd.get_dummies(X, drop_first=True)\n",
                        "X = X.fillna(X.median() if not X.empty else 0)\n",
                        "\n",
                        "if '" + task_type + "' == 'classification':\n",
                        "    le = LabelEncoder()\n",
                        "    y = le.fit_transform(y.astype(str))\n",
                        "\n",
                        "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
                        "\n",
                        "if '" + task_type + "' == 'classification':\n",
                        "    model = RandomForestClassifier(n_estimators=100, random_state=42)\n",
                        "else:\n",
                        "    model = RandomForestRegressor(n_estimators=100, random_state=42)\n",
                        "\n",
                        "model.fit(X_train, y_train)\n",
                        "print(\"Model training complete.\")"
                    ]
                },
                {
                    "cell_type": "code",
                    "execution_count": None,
                    "metadata": {},
                    "outputs": [],
                    "source": [
                        "# Evaluation\n",
                        "y_pred = model.predict(X_test)\n",
                        "if '" + task_type + "' == 'classification':\n",
                        "    print(classification_report(y_test, y_pred))\n",
                        "else:\n",
                        "    print(f\"RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.4f}\")\n",
                        "    print(f\"R2 Score: {r2_score(y_test, y_pred):.4f}\")"
                    ]
                }
            ])

        notebook = {
            "cells": cells,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3"
                },
                "language_info": {
                    "name": "python",
                    "version": "3.10"
                }
            },
            "nbformat": 4,
            "nbformat_minor": 5
        }
        
        return json.dumps(notebook, indent=2).encode('utf-8')

    @staticmethod
    def upload_to_supabase(content: bytes, filename: str, bucket: str = "outputs") -> Optional[str]:
        """Uploads generated data directly to Supabase Storage"""
        if not supabase:
            print("Supabase client not initialized, skipping upload.")
            return None
            
        try:
            # e.g. outputs/2026-04-20_14-22-00_generated_data.csv
            timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
            unique_filename = f"{timestamp}_{uuid.uuid4().hex[:6]}_{filename}"
            
            res = supabase.storage.from_(bucket).upload(unique_filename, content)
            
            # Return the public URL
            url_res = supabase.storage.from_(bucket).get_public_url(unique_filename)
            return url_res
        except Exception as e:
            err_msg = str(e)
            if "Bucket not found" in err_msg or "404" in err_msg:
                print("Supabase Storage: 'outputs' bucket not found. Skipping upload. Please create it in your Supabase dashboard.")
            else:
                print(f"Failed to upload to Supabase: {err_msg}")
            return None

    @staticmethod
    def log_pipeline_execution(message: str, schema_name: str = "default", status: str = "success") -> None:
        """Logs pipeline history to the Supabase Postgres Database"""
        if not supabase:
            print(f"[Supabase Offline Log] {message}")
            return
            
        try:
            supabase.table("pipeline_logs").insert({
                "message": message,
                "schema_name": schema_name,
                "status": status,
                "created_at": datetime.datetime.now().isoformat()
            }).execute()
        except Exception as e:
            err_msg = str(e)
            if "PGRST205" in err_msg or "pipeline_logs" in err_msg:
                print("Supabase Database: 'pipeline_logs' table not found. Skipping log. Please create it in your Supabase dashboard.")
            else:
                print(f"Failed to log to Supabase: {err_msg}")

export_service = ExportService()
